version: '3'
services:
  frontend:
    container_name: frontend-app
    build:
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      WATCHPACK_POLLING: 'true'

    volumes:
      - ./:/app
    command: ['npm', 'start']
