version: "3"
services:
  frontend:
    stdin_open: true
    tty: true
    container_name: frontend-app
    build:
      context: .clean
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
